version: '2.0'
networks: {}
services:
  otto_exercise:
    image: training/webapp:latest
    ports:
      - 8090:5000
    restart: always
    network_mode: bridge
    environment:
      - PROVIDER=world
    links:
      - database
    depends_on:
      - database
    command: /bin/bash -c "python tests.py && python app.py"
    volumes:
      - data:/data/webapp:rw
  database:
    image: mongo:3.4.4
    restart: always
    network_mode: bridge
    volumes:
      - data:/data/db:rw
volumes:
  data:
    driver: local
